### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by un-lock-me** [askerlee/vmfmix#2]
Hi,

Hope you can help me with this error,

I just runned the classeval.py and got this error

which argument I have to provide? may I ask you to explain

**Comment by un-lock-me** [comment]
Also when running wordclust I got this:
Not enough free arguments,
Also may I ask you to explain a bit about utils class and wordclus class?

I would really appreciate your help.

**Comment by askerlee** [comment]
Could you post some lines of your input file? 
BTW I didn't put wordclust.py on github. Were you using it?

**Comment by un-lock-me** [comment]
I just want to firstly run your code,
can you give me some instructions,
wordclust is there in your code, I thought maybe I should run other files firstly so evaluate will wwork on them.

for example there is no input file in your code(20news or reuters)
In summary I can not run your code without any changes

**Comment by askerlee** [comment]
Could you give a link to the wordclust file? I really couldn't find it.
20news and reuters data files are automatically generated using topicExp.py.
From your first post I suppose you want to evaluate LDA, not my method?

**Comment by un-lock-me** [comment]
sure,

this is the link for wordclust:
https://github.com/askerlee/vmfmix/blob/master/wordclust.py

you are right, but I said I have to run your code successfully then be able to apply on other thing,

it gives this error: return open(f, "rb")
IOError: [Errno 2] No such file or directory: '20news-train-11314.svm-reuters.txt'

**Comment by askerlee** [comment]
oops, sorry, I thought this issue is in topicvec. Yeah this file is in vmfmix.
You can download these test files:
https://www.dropbox.com/s/y53fyb732d2rcm7/test-data.rar?dl=0
These files are pulled out of my laptop. You might need to change the script a little bit to match these files. Anyway they are in the same format.

**Comment by un-lock-me** [comment]
Thank you 
Oh my mistake, I copied the 20news to your folder but didnt care about splitting to test and train data,
may please let me know how much testing and how much training data you have,

Also the accuracy is 99 is it really ok?

**Comment by askerlee** [comment]
20news and reuters have predefined split of training and test documents, so I didn't tune here. An accuracy of 99% might be due to a super large class which dominates the whole dataset. The classifier achieves high accuracy on that class but not so good on other classes. A macro-F1 makes more sense for unblanaced classes.

**Comment by un-lock-me** [comment]
you are right I just look at the training accuracy instead of test accuracy :| 
the last question for today, I am so sorry taking your time :(
1. there is no way to see the topics generated by your method?
2. I tried to find the method you are using for this structure: class labe: feature Index, value ,....

I found this :
import numpy as np
def loadUnigramFile(filename):
    UNI = open(filename)
    vocab_dict = {}
    wid = 1
    for line in UNI:
        line = line.strip()
        if line[0] == '#':
            continue
        fields = line.split("\t")
                             # id, freq, prob
        vocab_dict[ fields[0] ] = ( wid, int(fields[1]), np.exp(float(fields[2])) )
        wid += 1

    print ("%d words loaded from unigram file %s" %(wid, filename))
    return vocab_dict

so I wanted to use the same in my code,
I prepared a very very simple text input like this :

topic0 edu computer
topic1 don politics
topic2 music instrument

but when applying on my text it says :vocab_dict[ fields[0] ] = ( wid, int(fields[1]), np.exp(float(fields[2])) )
IndexError: list index out of range

do u have any idea of this?

**Comment by askerlee** [comment]
Oh I guess this function is used to load a unigram stat file used specifically for the TopicVec algorithm. It's not for generating input files for classEval.py. If you want to generate data files for classEval.py, please refer to topicExp.py. It generates the files for quite a few methods.

The utf-8 error you encountered seems to be caused by some non-ascii characters in your file. You could check if you accidentally turned on an input method for your language.

As to the question 1, actually I released a visualization code for the topics generated by TopicVec. It's at https://github.com/askerlee/topiccloud
It's not documented actually. But it takes the log file of topicvec as input and generates the cloud. You could see examples in the /clouds directory.

**Comment by un-lock-me** [comment]
oh sorry :(
so you mean this https://github.com/askerlee/topicvec/blob/master/topicExp.py

Also for visulization, its dynamic? I man it is going to visualize each topic model or working to visualize vmfmix?

thanks a lot :)

**Comment by askerlee** [comment]
Yeah this file.
The visualization code is not on the fly. You could finish training, get the log file, and run a script to extract an array. Then paste the array to gencloud.py to get the cloud... It's quite manual. Because the accompanying paper of this code is not published, I moved on to other works and stopped improving this code.

**Comment by un-lock-me** [comment]
I see,

I am really thankful for each explanation,
I will get back to you if I got an error but now it seems ok,
have a great day :)

**Comment by saria85** [comment]
the files in topicExp.py 
               unigramFilename = "top1grams-wiki.txt",
                word_vec_file = "25000-180000-500-BLK-8.0.vec",

can you explain about this please.
what is word-vec , I was supposed this will do all the process

**Comment by askerlee** [comment]
Word embedding is a continuous representation of words... It maps each word to a low dimensional real numbered vector. Word embeddings have many good properties and are widely used in current NLP methods. You could google and find a lot of introductory materials. For your purpose you could safely ignore the word embeddings and go straight to the file generation.

**Comment by saria85** [comment]
Actually I know the concept but when it comes to using in my project its kind of confusing,

the file seems one method, I would think I am not required to extract some part of that code to use in my project but I should call that totally,

Really thanks for bearing with my simple  simple questions,
